kind: Service
apiVersion: v1
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: PLACEHOLDER_SERVICE_NAME
spec:
  type: NodePort
  selector:
    app: PLACEHOLDER_SERVICE_NAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: PLACEHOLDER_SERVICE_NAME
  annotations:
    alb.ingress.kubernetes.io/group.name: general
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: PLACEHOLDER_CERT_ARN
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
  - host: PLACEHOLDER_HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: PLACEHOLDER_SERVICE_NAME
            port:
              number: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: PLACEHOLDER_SERVICE_NAME
  labels:
    app: PLACEHOLDER_SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PLACEHOLDER_SERVICE_NAME
  template:
    metadata:
      labels:
        app: PLACEHOLDER_SERVICE_NAME
    spec:
      containers:
      - name: PLACEHOLDER_SERVICE_NAME
        image: PLACEHOLDER_DOCKER_IMAGE
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["python","configure.py"]
      nodeSelector:
        nodeGroupType: general